echo "================ Usage ================"
echo "* Usage of tcpcl:"
echo "   - Enter "./tcpcl" without quaters."
echo "   - At the same string type ip address"
echo "     of a getter."
echo "   - At the same string type opened"
echo "     port of the getter."
echo "   - At the string type your message IN"
echo "     quaters."
echo "======================================="
echo "* Usage of tcpserv:"
echo "   - Enter ip and port of your server."
echo "   - If an error occured you can see"
echo "     the problem in log for today."
echo "   - Message from clients you would see"
echo "     in the server`s window."
echo "======================================="
echo "* P.S.:"
echo "   - If some parameters were not"
echo "     pointed, each program would ask"
echo "     for explicit pointing of the"
echo "     parameters."
echo "   - Tcpserv works in auto mode, you"
echo "     don`t have to enter ip, only port."
echo "     You should type 23 as a port."
echo "======================================="
read -n1 -r -p "Press any key to continue..." key
